version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12" # Using 3.12 for maximum stability with current MkDocs plugins

# Tell Read the Docs to use MkDocs instead of Sphinx
mkdocs:
  configuration: mkdocs.yml

# Install the Material theme and MkDocs via your root requirements file
python:
  install:
    - requirements: requirements.txt
