site_name: FRC Team 2064 Robotics Guide
site_description: Getting started in FRC is AMAZING!!
site_author: Team 2064 - The Panther Project
copyright: FRC Team 2064 ~ The Panther Project

theme:
  name: material
  js:
    - features/privacy.js
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: img/favicon.ico

features:
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.footer
    - privacy.consent
    - privacy.cookies
    - toc.integrate
    - content.lightbox
    - content.code.highlight

extra_javascript:
  - js/image-zoom.js
  - js/custom.js
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/javascript.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/java.min.js

extra_css:
    - css/custom.css
    - css/image-zoom.css
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/base16/material-darker.min.css

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
nav:
  - Home: index.md
  - XRP Bot Creation: xrp-bot.md
  - Build: Build.md
  - Programming: Programming.md
  - CAD: CAD.md