site_name: FRC Team 2064 Robotics Guide
site_description: Getting started in FRC is AMAZING!!
site_author: Team 2064 - The Panther Project
copyright: FRC Team 2064 ~ The Panther Project

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: img/favicon.ico

features:
  - content.code.copy
  - content.code.annotate
  - content.tabs.link
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.path
  - navigation.footer
  - toc.integrate
  - content.code.highlight

extra_javascript:
  - js/features/privacy.js
  # - js/custom.js  # Temporarily disabled for testing

extra_css:
  # - css/custom.css  # Temporarily disabled for testing

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

plugins:
  - search

nav:
  - Home: index.md
  - XRP Bot Creation: xrp-bot.md
  - Build: Build.md
  - Programming: Programming.md
  - CAD: CAD.md