site_name: FRC Team 2064 Robotics Guide
site_description: Getting started in FRC is AMAZING!!
site_author: Team 2064 - The Panther Project
copyright: Copyright &copy; 2025 FRC Team 2064
  </br>
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
  favicon: img/favicon.ico

features:
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.footer
    - privacy.consent
    - privacy.cookies
    - toc.integrate
    - content.lightbox

extra_javascript:
  - js/image-zoom.js

extra_css:
    - css/custom.css
    - css/image-zoom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/frc2064/
      name: frc2064
  cookies:
    analytics:
      name: Google Analytics
      checked: false
      description: >-
        Allows us to analyze how our site is used and improve user experience.
    marketing:
      name: Marketing Cookies
      checked: false
      description: Used for targeted advertising and tracking across sites.

plugins:
  - search
nav:
  - Home: index.md
  - XRP Bot Creation: xrp-bot.md
  - Build: Build.md
  - Programming: Programming.md
  - CAD: CAD.md