site_name: FRC Team 2064 Robotics Guide
site_description: Getting started in FRC is AMAZING!!
site_author: Team 2064 - The Panther Project

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: null
  favicon: null
  extra_css:
    - css/extra.css
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  

nav:
  - Home: index.md
  - XRP Bot Creation: xrp-bot.md
  - Build: Build.md
  - Programming: Programming.md