nav:
  Safety:
    - Safety: safety/Safety.md
    - Safetyquiz: safety/Safetyquiz.md
  XRP:
    - xrp-bot: xrp/xrp-bot.md
    - Build: xrp/Build.md
    - gettingtoknow: xrp/gettingtoknow.md
    - basicdriveXRP: xrp/basicdriveXRP.md
    - XRPdrivechallenge: xrp/XRPdrivechallenge.md
    - Ping-Pong-Launcher-Challenge: xrp/Ping-Pong-Launcher-Challenge.md
    - PingPongAssemble: xrp/PingPongAssemble.md
    - wiringpingpongxrp: xrp/wiringpingpongxrp.md
    - pingpongcode: xrp/pingpongcode.md
    - PingPongCompetition: xrp/PingPongCompetition.md
  Engineering:
    - designprocess: engineering/designprocess.md
    - bumpers: engineering/bumpers.md
    - CAD: engineering/CAD.md
    - cadonshapecourse: engineering/cadonshapecourse.md
    - WPIlib: engineering/WPIlib.md
    - advancedjava: engineering/advancedjava.md
  Shop:
    - Closet: shop/Closet.md
    - Handtools: shop/Handtools.md
    - crimping: shop/crimping.md
    - handtoolsquiz: shop/handtoolsquiz.md
    - 3dprinting: shop/3dprinting.md
    - bandsaw: shop/bandsaw.md
    - lathe: shop/lathe.md
    - millingmachine: shop/millingmachine.md
    - cncrouter: shop/cncrouter.md
    - laserengraver: shop/laserengraver.md
    - machinelessons: shop/machinelessons.md
  Media:
    - cricut: media/cricut.md
    - buttonmaker: media/buttonmaker.md
    - photoshop: media/photoshop.md
    - illustrator: media/illustrator.md
    - branding: media/branding.md
    - publicspeaking: media/publicspeaking.md
  Resources:
    - frckeywords: resources/frckeywords.md
    - rubric: resources/rubric.md