name: Deploy to DreamHost
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to DreamHost
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: frc2064.com
          REMOTE_USER: brimar70
          SOURCE: "site/"
          TARGET: "/home/brimar70/frc2064.com/"
          ARGS: "-rlgoDzvc --delete"
